# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from golang v1.11 base image
FROM golang:1.11

# Add Maintainer Info
LABEL maintainer="Xiaoxin"

# Set the Current Working Directory inside the container
WORKDIR $GOPATH/

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
copy . . 

RUN cd $GOPATH/src
# Download all the dependencies
# https://stackoverflow.com/questions/28031603/what-do-three-dots-mean-in-go-command-line-invocations
RUN go get -d -v ./...

# Install the package
RUN go install -v ./...
#RUN go install -v ./...

# This container exposes port 80 to the outside world
EXPOSE 80

# Run the executable
CMD ["./bin/server"]